
parameters:
    uploads_rooms_directory: "%kernel.project_dir%/public/uploads/users"
services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'


    App\Controller\UserController:
        arguments:
            $uploadsUsersDirectory: "%uploads_users_directory%"